apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: doh-system

resources:
  - namespace.yaml
  - configmap-coredns.yaml
  - configmap-nginx.yaml
  - coredns-smartdns.yaml
  - doh-backend.yaml
  - doh-nginx.yaml
  - networkpolicy.yaml
  - pdb.yaml

commonLabels:
  app.kubernetes.io/part-of: doh-smart-dns
  app.kubernetes.io/managed-by: kustomize
